# mpf-monitor

# todo
# tests
# test against the multiple versions of MPF that are supported
# load the graphics environment to make sure everything works?

language: python

python:
  - "3.4"

install:
  - pip3 install --upgrade setuptools pip twine

script:
  - python3 setup.py install;

deploy:
  provider: pypi
  user: jabdoa
  password:
    secure: "VLYW6yrjVv9ZTlYkH7bU/L8e44IV1G8+LAaZLbRTgL1iOwJsQj+2r5qogleQyyx7Hfe5vLXLDGi2jW89nxB8/dKUNvut7+puPErgWCIS9s2GHisRTQKmIv6YsMpkwRIGP07ppZtjPyaIn9fR/Pv3urnmHFjiLQoeDnHU5qc6/ssFHIUOPYtNbFNqMs4+IWos5FuN3nIJbXLLOHiqnpr4ommawY1G1irnsI7OfkEa4WrdsR3k2Dt/ps17wgicDQtw3igN7j0tXyqsoh419WLb3YBwO2flkXYgGUA3dqMoARGrYqQU68PR87IXoBdxyDXXmvufwV2RUol+dnnj3vWdtsibYc0l5TpTDFlQLsgVDpL+n0dVX9gUb/1St4bO5tHFHoqSCvUagtpFcC8ilIoUb2hKsiWgG3mzA9pcvuwB+cRq39bvmGwOBw3lduKpqKnAmtVLbeh+jqLnnZIUuocQlQJzIWVaUNJkXDVsFvj07f/pMEM8RYkp/ICnXgirXaFbO7bHkPlhZ7Skk5fbSE/JZ2xdiwdEzBpKhmxaXotSFppSqs8J9j7+BS1DC6tu2ISwfANtKRqafNckQ0E+44dtt+Skcm2UKhmq2P7pt7MZ3ko0fIGG3dkV50O60em2hKk+IrHw2mnsQefETZHUvc7C5juo7y6q4EbBLLHt2PgI1p0="
  on:
    repo: missionpinball/mpf-monitor
    all_branches: true
